import { HIDDEN, isSuperHidden, isUltraHidden } from './hidden-data';
// 현대판 가문 명성 직업군: 정·관계, 과학·의료, 경제, 문화, 숨은 영웅.
// 모두 게임 안의 직업에서 출발해 "정점 이벤트"로 얻는다. 선행 카드가 필요한 것, 2단계 도전인 것도 있다.
import type { CardDef, Summit } from './cards';
import type { GameState, Person, StatKey } from './types';
import { age, fullName, hasFlag } from './people';

const ST = (p: Person, k: StatKey, v: number) => p.actual[k] >= v;
const has = (s: GameState, p: Person, id: string) => (s.cards ?? []).some((c) => c.id === id && c.personId === p.id);
const jobIn = (p: Person, jobs: string[], min = 0) => jobs.includes(p.job) && p.jobLevel >= min;
import { homeCity, pledgeOf } from './stories-politics';
const setJob = (job: string, lv: number) => (_s: GameState, p: Person) => {
  p.job = job;
  p.jobLevel = lv;
  p.jobYears = 25;
};

export const MORE_CARDS: CardDef[] = [
  // 히든 직업 카드: 그 직업이 되면 얻는다 (뒷면 공략법 포함)
  ...HIDDEN.map((h): CardDef => ({ id: h.id, name: `히든: ${h.name}`, icon: h.icon, rarity: isSuperHidden(h.id) || isUltraHidden(h.id) ? 'legend' : 'epic', hidden: true, how: h.strategy || `??? ${h.hint}`, eff: h.eff, auto: (_s, p) => p.job === h.id })),
  // 명의의 칭호: 국빈급 환자를 살려 냈을 때 (vip-cure.ts)
  { id: 'god_medicine', name: '의술의 신', icon: '⚕️', rarity: 'legend', how: '전문의 이상의 의사에게 드물게 오는 극비 진료(미국 대통령·국왕 등)에서 환자를 살려 낸다 · 지능·성품·직급·[약손]·[수재]·의료 적성이 확률을 높인다', eff: { fame: 4, hp: 2, kid: 'int' }, auto: (_s, p) => hasFlag(p, 'god_medicine') },
  { id: 'god_acupuncture', name: '침술의 신', icon: '🪡', rarity: 'legend', how: '한의사에게 드물게 오는 극비 왕진(국빈·세계적 인물)에서 침으로 살려 낸다 · 지능·성품·직급·[약손]·의료 적성이 확률을 높인다', eff: { fame: 4, hp: 3, kid: 'mor' }, auto: (_s, p) => hasFlag(p, 'god_acupuncture') },
  // 정·관계·공공
  { id: 'chief_of_staff', name: '합참의장·참모총장', icon: '🎖', rarity: 'legend', how: '「별을 단 장군」 카드 → 참모총장 임명 (2단계)', eff: { fame: 4, kid: 'str' }, honor: 'taeguk' },
  { id: 'police_chief', name: '경찰청장', icon: '🚓', rarity: 'epic', how: '총경까지 오른 경찰관 → 청장 내정', eff: { fame: 2, heat: 3 }, honor: 'hongjo' },
  { id: 'fire_chief', name: '소방청장', icon: '🧯', rarity: 'epic', how: '소방경 이상 소방관 → 소방청장', eff: { fame: 2, hp: 1 }, honor: 'dongbaek' },
  { id: 'constitutional', name: '헌법재판관', icon: '📜', rarity: 'legend', how: '고참 판사 → 헌법재판관 지명 (2단계)', eff: { fame: 3, heat: 4 } },
  { id: 'un_sg', name: 'UN 사무총장', icon: '🇺🇳', rarity: 'legend', tier: 3, how: '「특명전권대사」 카드 + 50세 이상 → 안보리 선출 (2단계)', eff: { fame: 8, kid: 'cha' }, honor: 'gwanghwa' },
  { id: 'bok_governor', name: '한국은행 총재', icon: '🏦', rarity: 'legend', how: '은행 지점장 이상·리서치센터장 이상·경제학 교수 → 총재 임명 (2단계)', eff: { fame: 3, cash: 3000 }, honor: 'cheongjo' },
  { id: 'mayor', name: '시장 (광역·기초단체장)', icon: '🏙', rarity: 'legend', how: '국회의원 경력 + 가문 명성 80 → 사는 도시의 시장 선거 (경선·본선·개표)', eff: { fame: 5 } },
  { id: 'spymaster', name: '국정원장·블랙 요원', icon: '🕶', rarity: 'epic', how: '고참 장교·경찰·외교관·보안 전문가 → 비밀 작전', eff: { heat: 5, kid: 'int' }, honor: 'gukseon' },
  { id: 'cyber_commander', name: '국방사이버사령관', icon: '🛡', rarity: 'epic', how: '리드급 보안 전문가·개발자·데이터 과학자 → 국가 해킹 방어', eff: { kid: 'int', fame: 1 }, honor: 'gukseon' },
  // 과학·의료
  { id: 'astronaut', name: '우주비행사', icon: '🚀', rarity: 'legend', how: '항공우주 엔지니어·조종사·연구원·장교 (지능 65·건강 60) → 선발과 비행 (2단계)', eff: { fame: 5, kid: 'int' }, honor: 'ungbi' },
  { id: 'who_hero', name: 'WHO 사무총장·팬데믹 영웅', icon: '🌍', rarity: 'legend', how: '「명의」 카드 → 세계 보건 위기 (2단계)', eff: { fame: 5, hp: 2 }, honor: 'mugunghwa_nat' },
  { id: 'new_drug', name: '글로벌 신약 개발자', icon: '💊', rarity: 'epic', how: '연구원·약사·의사·교수 (논문 15편) → 임상 3상', eff: { cash: 12000, hp: 1 }, honor: 'hyeoksin' },
  { id: 'turing', name: '튜링상 AI 석학', icon: '🤖', rarity: 'legend', how: '개발자·데이터 과학자·연구원·교수 (논문 25편 또는 고참) → 세계적 AI 논문 (2단계)', eff: { kid: 'int', fame: 4 }, honor: 'changjo' },
  { id: 'msf', name: '국경없는의사회 구호활동가', icon: '⛑', rarity: 'epic', how: '의사·간호사·응급구조사 (도덕성 60) → 분쟁 지역 파견', eff: { fame: 3, hap: 1 }, honor: 'moran' },
  // 경제·산업
  { id: 'bigtech', name: '빅테크 창업주', icon: '💻', rarity: 'legend', how: '중견기업 이상 창업가 (지능 65) → AI 혁신 (2단계)', eff: { cash: 50000, fame: 3 }, honor: 'geumtap' },
  { id: 'hedge_fund', name: '글로벌 헤지펀드 매니저', icon: '📈', rarity: 'epic', how: '고참 애널리스트·은행원 → 월가 진출', eff: { cash: 15000 } },
  { id: 'ent_chair', name: '엔터테인먼트 그룹 의장', icon: '🎙', rarity: 'legend', how: '스타 연예인·가수·배우 (40세 이상) 또는 중견 창업가 → K-콘텐츠 기획사', eff: { cash: 20000, fame: 3 }, honor: 'geumgwan' },
  { id: 'media_mogul', name: '미디어 그룹 회장', icon: '📡', rarity: 'epic', how: '중견 창업가·본부장급 PD·논설위원급 기자 → 방송사 인수', eff: { cash: 8000, fame: 2 } },
  { id: 'space_founder', name: '민간 우주기업 창업자', icon: '🛰', rarity: 'legend', tier: 3, how: '「빅테크 창업주」 또는 「우주비행사」 카드 → 로켓 발사 (2단계)', eff: { cash: 30000, fame: 6 }, honor: 'ungbi' },
  { id: 'philanthropist', name: '기부왕 재단 이사장', icon: '🤲', rarity: 'epic', how: '누적 기부 3억 원 (행동 탭 장학금 기부 등)', eff: { fame: 3, hap: 2 }, honor: 'mugunghwa_nat', auto: (_s, p) => (p.donated ?? 0) >= 30000 },
  { id: 'heritage_master', name: '국가무형문화재 보유자', icon: '🏺', rarity: 'legend', how: '「대한민국 명장」 카드 또는 25년 넘은 목수·요리사·화가·음악가 → 지정 심사', eff: { fame: 3, kid: 'mor' } },
  // 문화·예술
  { id: 'maestro', name: '세계적 지휘자·거장', icon: '🎼', rarity: 'legend', how: '전국 투어급 음악가 (매력 70) → 베를린 필 데뷔 (2단계)', eff: { fame: 4, hap: 2 }, honor: 'geumgwan' },
  { id: 'cannes', name: '칸 영화제 수상', icon: '🌴', rarity: 'legend', how: '「청룡영화상 주연상」 카드 또는 본부장급 PD → 칸 경쟁 부문 (2단계)', eff: { fame: 5, cash: 5000 }, honor: 'geumgwan' },
  { id: 'mega_creator', name: '구독자 5천만 메가 크리에이터', icon: '📱', rarity: 'epic', how: '유튜버 최고 단계 (구독자 500만) — 자동', eff: { cash: 15000, fame: 2 }, auto: (_s, p) => p.job === 'youtuber' && p.jobLevel >= 5 },
  { id: 'pulitzer', name: '퓰리처상 탐사보도 기자', icon: '🗞', rarity: 'legend', how: '차장급 이상 기자 (도덕성 65) → 거대 비리 추적 (2단계)', eff: { fame: 4, heat: 3 } },
  { id: 'grammy', name: '그래미 수상 프로듀서', icon: '🏆', rarity: 'legend', how: '「국민 가수」 또는 「빌보드 1위」 카드 → 그래미 (2단계)', eff: { cash: 10000, fame: 4 }, honor: 'geumgwan' },
  { id: 'esports_owner', name: 'e스포츠 구단주', icon: '🕹', rarity: 'epic', how: '「e스포츠 월드 챔피언」 카드 또는 창업가 → 구단 창단', eff: { cash: 3000, kid: 'int' } },
  { id: 'great_author', name: '노벨문학상 대문호', icon: '🖋', rarity: 'legend', tier: 3, how: '문학상을 받은 소설가 → 한림원 발표 (2단계)', eff: { fame: 6, kid: 'int' }, honor: 'geumgwan' },
  // 숨은 영웅
  { id: 'eco_hero', name: '타임 올해의 인물 (기후 활동가)', icon: '🌱', rarity: 'epic', how: '도덕성 72 이상 + 가문 명성 40 → 기후 운동', eff: { fame: 3, hp: 1 } },
  { id: 'profiler', name: '전설의 프로파일러', icon: '🔍', rarity: 'epic', how: '경사 이상 경찰관 (지능 60) → 연쇄 사건', eff: { fame: 2, heat: 2 } },
  { id: 'explorer', name: '극지·심해 탐험가', icon: '🧭', rarity: 'epic', how: '근력·건강 62 이상 운동선수·장교·연구원·항해사·사진작가·트레이너 → 탐험대', eff: { kid: 'str', fame: 2 } },
  { id: 'cardinal', name: '추기경·대종사', icon: '⛪', rarity: 'legend', how: '담임목사급 종교인 (도덕성 70) → 추대 (2단계)', eff: { hap: 3, fame: 3 }, honor: 'mugunghwa_nat' },
  { id: 'conscience', name: '시대의 양심 (민주화·인권 운동가)', icon: '🕯', rarity: 'epic', how: '기자·변호사·교수·종교인·사회복지사·작가 (도덕성 75) → 거리의 양심', eff: { fame: 3, kid: 'mor' }, honor: 'moran' },

  // ───────── ★1 입문 카드: 어떤 직업이든 성실히 일하면 닿을 수 있는 명예 ─────────
  { id: 'model_civil', name: '청백리 공무원', icon: '🏛', rarity: 'rare', tier: 1, how: '공무원·세무·집배원·교도관·공기업 (직급 1 이상) → 청렴 표창', eff: { fame: 1, heat: 2 } },
  { id: 'best_teacher', name: '올해의 스승', icon: '🍎', rarity: 'rare', tier: 1, how: '교사·유치원 교사·강사·사서 → 스승의 날 표창', eff: { study: 1 } },
  { id: 'sales_king', name: '영업왕', icon: '🥇', rarity: 'rare', tier: 1, how: '회사원·대기업·영업·보험·마케터·무역·은행 → 연말 시상', eff: { cash: 800 } },
  { id: 'engineer_award', name: '올해의 엔지니어', icon: '⚙️', rarity: 'rare', tier: 1, how: '개발자·연구원·엔지니어·건축가 → 사내 기술상', eff: { kid: 'int' } },
  { id: 'service_master', name: '서비스 명인', icon: '🎀', rarity: 'rare', tier: 1, how: '요리사·바리스타·미용사·호텔리어·승무원 등 서비스직 → 친절 명인', eff: { hap: 1, cash: 400 } },
  { id: 'good_driver', name: '무사고 모범 기사', icon: '🚌', rarity: 'rare', tier: 1, how: '택배·배달·택시·버스·화물·기관사·항해사 (5년 이상) → 무사고 표창', eff: { hp: 1 } },
  { id: 'local_legend', name: '동네 맛집·명물 사장', icon: '🏮', rarity: 'rare', tier: 1, how: '치킨집·카페·편의점·쇼핑몰·식당·창업가 → TV 생활 프로그램', eff: { cash: 1000, hap: 1 } },
  { id: 'angel_care', name: '백의의 천사', icon: '🤍', rarity: 'rare', tier: 1, how: '간호·재활·임상·응급구조·요양·수의 (5년 이상) → 봉사상', eff: { hp: 1, hap: 1 } },
  { id: 'pro_license', name: '업계의 명인', icon: '📑', rarity: 'rare', tier: 1, how: '변호사·회계사·세무사·변리사·법무사·노무사·관세사·중개사 → 협회 공로상', eff: { cash: 800, heat: 2 } },
  { id: 'craft_hands', name: '숙련의 손', icon: '🔨', rarity: 'rare', tier: 1, how: '생산·전기·용접·정비·목수·배관·조선·크레인 (5년 이상) → 기능 우수상', eff: { kid: 'str' } },
  { id: 'rookie_star', name: '떠오르는 신예', icon: '🌠', rarity: 'rare', tier: 1, how: '연예인·배우·모델·가수·작가·화가·유튜버·기자·PD·운동선수·게이머 → 신인상', eff: { fame: 1 } },
  { id: 'farm_hero', name: '땅의 사람', icon: '🌽', rarity: 'rare', tier: 1, how: '농부·스마트팜·어부·축산 → 풍년 표창', eff: { hp: 1, cash: 500 } },
  { id: 'public_servant', name: '제복의 명예', icon: '🎗', rarity: 'rare', tier: 1, how: '경찰·해경·소방·군인·외교관·판사·검사 → 모범 공무원', eff: { fame: 1, kid: 'mor' } },
  { id: 'good_heart', name: '나눔의 손길', icon: '💝', rarity: 'rare', tier: 1, how: '사회복지사·종교인·의사·치과의사·한의사·약사 → 지역 봉사상', eff: { hap: 2 } },
  // 가족 카드: 직업과 상관없이
  { id: 'proud_parent', name: '장한 어버이', icon: '👨‍👩‍👧‍👦', rarity: 'rare', tier: 1, how: '자녀 셋 이상을 키운 50세 이상 — 자동', eff: { hap: 2 }, auto: (s, p) => age(s, p) >= 50 && p.childIds.length >= 3 },
  { id: 'centenarian', name: '백세 어르신', icon: '🎂', rarity: 'epic', tier: 1, how: '95세 이상 장수 — 자동', eff: { hp: 1, hap: 2 }, auto: (s, p) => age(s, p) >= 95 },
  { id: 'filial', name: '효자·효녀상', icon: '🙇', rarity: 'rare', tier: 1, how: '부모를 모시는 따뜻한 자녀 (도덕성 55) → 효행상', eff: { hap: 1, kid: 'mor' } },
];

type S = Summit;
const n = (p: Person) => fullName(p);
export const MORE_SUMMITS: S[] = [
  { card: 'chief_of_staff', title: '🎖 참모총장 임명', stages: 2, pre: 'general', ok: (s, p) => has(s, p, 'general') && p.job === 'officer', setup: setJob('officer', 6),
    text: (c) => `국방부가 ${n(c.p)} 장군을 차기 참모총장 후보로 올렸다. 청문회급 검증과 대통령 면담이 기다린다.`,
    a: ['작전 능력으로 증명한다', 'int', 70, '🎖 참모총장 취임! 4성 장군의 별이 빛난다.', '다른 동기가 낙점됐다.'],
    b: ['장병 복지 개혁안을 내건다', 'mor', 65, '🎖 "병사를 먼저 생각하는 총장" 취임!', '"정치적"이라는 비판에 밀렸다.'] },
  { card: 'police_chief', title: '🚓 경찰청장 내정', ok: (_s, p) => jobIn(p, ['police'], 6), setup: setJob('police', 6),
    text: (c) => `${n(c.p)} 총경이 파격 발탁으로 경찰청장 후보가 됐다.`,
    a: ['민생 치안 공약', 'cha', 62, '🚓 경찰청장 취임! 14만 경찰의 수장이 됐다.', '청문회에서 과거 사건이 발목을 잡았다.'],
    b: ['조직 개혁 공약', 'int', 62, '🚓 개혁 청장 취임!', '내부 반발로 낙마했다.'] },
  { card: 'fire_chief', title: '🧯 소방청장', ok: (_s, p) => jobIn(p, ['firefighter'], 4), setup: setJob('firefighter', 5),
    text: (c) => `30년 현장을 지킨 ${n(c.p)}에게 소방청장 제의가 왔다.`,
    a: ['현장 경험을 앞세운다', 'str', 55, '🧯 소방청장 취임! 첫 현장 출신 청장이다.', '행정 경험 부족으로 밀렸다.'],
    b: ['소방관 처우 개선 공약', 'mor', 58, '🧯 취임! 소방관들이 환호했다.', '예산 당국에 막혔다.'] },
  { card: 'constitutional', title: '📜 헌법재판관 지명', stages: 2, ok: (_s, p) => jobIn(p, ['judge'], 4), setup: setJob('judge', 4),
    text: (c) => `대법원장이 ${n(c.p)} 판사를 헌법재판관 후보로 지명했다.`,
    a: ['소수의견의 소신을 밝힌다', 'mor', 66, '📜 헌법재판관 취임! 역사에 남을 결정문을 쓸 것이다.', '국회 동의가 부결됐다.'],
    b: ['법리의 정밀함으로 승부', 'int', 68, '📜 취임! "헌법의 수호자".', '청문회에서 흔들렸다.'] },
  { card: 'un_sg', title: '🇺🇳 UN 사무총장 선거', stages: 2, pre: 'ambassador', ok: (s, p) => has(s, p, 'ambassador') && age(s, p) >= 50, setup: (s, p) => (setJob('diplomat', 5)(s, p), (p.birthYear = s.year - 58)),
    text: (c) => `정부가 ${n(c.p)} 대사를 UN 사무총장 후보로 추천했다. 안보리 5개 상임이사국 모두의 거부권을 피해야 한다.`,
    a: ['강대국을 한 곳씩 설득한다', 'cha', 74, '🇺🇳 UN 사무총장 선출! 세계의 대통령이 됐다.', '한 상임이사국이 거부권을 행사했다.'],
    b: ['평화 중재 실적을 내세운다', 'mor', 70, '🇺🇳 만장일치로 선출! 전 세계 언론이 주목한다.', '표 대결에서 밀렸다.'] },
  { card: 'bok_governor', title: '🏦 한국은행 총재', stages: 2, ok: (_s, p) => jobIn(p, ['banker'], 5) || jobIn(p, ['analyst'], 4) || (p.job === 'professor' && p.jobLevel >= 2 && p.flags.includes('major:econ')), setup: setJob('banker', 6),
    text: (c) => `물가와 환율이 요동친다. 대통령실이 ${n(c.p)}을(를) 한국은행 총재 후보로 검토한다.`,
    a: ['금리 인상으로 물가를 잡겠다', 'int', 70, '🏦 한국은행 총재 취임! 한마디에 시장이 움직인다.', '"시장을 모른다"는 평에 낙마.'],
    b: ['시장과의 소통을 약속한다', 'cha', 64, '🏦 총재 취임! 시장이 안도했다.', '청문회에서 부동산 문제가 불거졌다.'] },
  { card: 'mayor', title: '🏙 시장 선거', stages: 2, ok: (s, p) => (p.job === 'politician' || p.flags.includes('was_politician')) && s.fame >= 80, setup: (s, p) => (setJob('politician', 2)(s, p), (s.fame = 120)),
    text: (c) => `${n(c.p)}이(가) ${homeCity(c.s, c.p)}시장 선거에 나선다. 당내 경선부터 본선까지. 대표 공약은 "${pledgeOf(c.s, { ...c.p, job: 'mayor' }, c.ev.uid)}".`,
    a: ['교통·주거 공약으로', 'int', 64, '🏙 시장 당선! 차기 대권 주자로 떠올랐다.', '낙선. 그래도 정치적 체급이 올랐다.'],
    b: ['골목 유세로 발로 뛴다', 'cha', 66, '🏙 당선! 시민들이 "우리 시장"이라 부른다.', '근소한 차이로 졌다.'] },
  { card: 'spymaster', title: '🕶 비밀 작전', ok: (_s, p) => jobIn(p, ['officer', 'police', 'diplomat', 'security'], 3), setup: setJob('officer', 4),
    text: (c) => `국정원에서 ${n(c.p)}에게 조용히 연락이 왔다. 해외 산업 스파이 조직을 무너뜨리는 작전. 가족에게도 비밀이다.`,
    a: ['잠입한다', 'int', 62, '🕶 작전 성공. 공개되지 않는 훈장이 가족 금고에 들어갔다.', '신분이 노출돼 급히 귀국했다.'],
    b: ['정보망을 짠다', 'cha', 60, '🕶 조직을 일망타진. 훗날 국정원장 후보로 거론된다.', '정보원이 배신했다.'] },
  { card: 'cyber_commander', title: '🛡 국가 사이버 공격', ok: (_s, p) => jobIn(p, ['security', 'developer', 'data_scientist'], 3), setup: setJob('security', 4),
    text: (c) => `새벽, 국가 전산망에 대규모 사이버 공격. 국방부가 민간 최고 전문가 ${n(c.p)}을(를) 긴급 호출했다.`,
    a: ['실시간 역추적', 'int', 66, '🛡 공격을 막고 배후까지 밝혀냈다! 사이버사령관으로 발탁.', '막았지만 배후는 못 찾았다.'],
    b: ['백신을 전국에 배포', 'mor', 55, '🛡 전국 전산망을 지켰다. 보국훈장.', '배포가 늦어 피해가 일부 났다.'] },
  { card: 'astronaut', title: '🚀 우주비행사 선발', stages: 2, ok: (_s, p) => ['aero_engineer', 'pilot', 'researcher', 'officer'].includes(p.job) && ST(p, 'int', 65) && ST(p, 'hp', 60), setup: (s, p) => (setJob('aero_engineer', 3)(s, p), (p.actual.int = 90), (p.actual.hp = 90)),
    text: (c) => `한국 유인 달 탐사 계획. 3만 명이 지원한 우주비행사 선발에 ${n(c.p)}이(가) 최종 후보에 올랐다.`,
    a: ['극한 체력 훈련', 'hp', 70, '🚀 발사 성공! 대한민국 국기를 우주에 꽂았다.', '원심분리기 훈련에서 탈락했다.'],
    b: ['임무 시뮬레이션', 'int', 72, '🚀 임무 사령관으로 우주에 갔다!', '마지막 평가에서 밀렸다.'] },
  { card: 'who_hero', title: '🌍 세계 보건 위기', stages: 2, pre: 'famed_doctor', ok: (s, p) => has(s, p, 'famed_doctor'), setup: setJob('doctor', 4),
    text: (c) => `신종 감염병이 대륙을 휩쓴다. WHO가 ${n(c.p)}에게 국제 대응팀장을 맡아 달라고 한다.`,
    a: ['현장으로 날아간다', 'mor', 68, '🌍 확산을 막아냈다! WHO 사무총장으로 추대됐다.', '감염돼 귀국했다. 다행히 회복했다.'],
    b: ['백신 공동 개발을 이끈다', 'int', 72, '🌍 백신 개발 성공. 인류를 구한 의사로 기록된다.', '임상이 실패했다.'] },
  { card: 'new_drug', title: '💊 임상 3상', ok: (_s, p) => ['researcher', 'pharmacist', 'doctor', 'professor', 'chip_engineer'].includes(p.job) && (p.papers ?? 0) >= 15, setup: (s, p) => (setJob('researcher', 3)(s, p), (p.papers = 20)),
    text: (c) => `${n(c.p)}이(가) 발견한 항암 후보 물질이 임상 3상에 들어간다. 10년의 연구가 판가름 난다.`,
    a: ['데이터를 끝까지 파고든다', 'int', 66, '💊 FDA 승인! 전 세계 환자에게 쓰인다. 특허료가 쏟아진다.', '3상에서 효능 입증 실패.'],
    b: ['글로벌 제약사와 손잡는다', 'cha', 60, '💊 기술 수출 1조 원! 신약이 세상에 나왔다.', '계약이 무산됐다.'] },
  { card: 'turing', title: '🤖 세계적 AI 논문', stages: 2, ok: (_s, p) => ['developer', 'data_scientist', 'researcher', 'professor'].includes(p.job) && ((p.papers ?? 0) >= 25 || p.jobLevel >= 4), setup: (s, p) => (setJob('data_scientist', 4)(s, p), (p.papers = 30)),
    text: (c) => `${n(c.p)}의 AI 알고리즘이 세계 학계를 뒤흔든다. 인용 수가 폭발 중이다.`,
    a: ['오픈소스로 공개한다', 'mor', 62, '🤖 튜링상 수상! 컴퓨터 과학의 노벨상이다.', '다른 연구팀이 먼저 발표했다.'],
    b: ['후속 연구로 완성한다', 'int', 74, '🤖 튜링상 수상! 시대의 패러다임을 바꿨다.', '후속 연구가 막혔다.'] },
  { card: 'msf', title: '⛑ 분쟁 지역 파견', ok: (_s, p) => ['doctor', 'nurse', 'emt'].includes(p.job) && ST(p, 'mor', 60), setup: (s, p) => (setJob('doctor', 2)(s, p), (p.actual.mor = 80)),
    text: (c) => `국경없는의사회가 ${n(c.p)}에게 분쟁 지역 파견을 요청했다. 6개월, 포탄 소리가 들리는 병원이다.`,
    a: ['간다', 'mor', 62, '⛑ 수천 명을 살리고 돌아왔다. 국민훈장.', '위험해져 3개월 만에 철수했다.'],
    b: ['현지 의료진을 가르친다', 'int', 58, '⛑ 현지 병원이 스스로 설 수 있게 됐다.', '언어 장벽에 막혔다.'] },
  { card: 'bigtech', title: '💻 AI 혁신', stages: 2, ok: (_s, p) => jobIn(p, ['founder'], 3) && ST(p, 'int', 65), setup: (s, p) => (setJob('founder', 4)(s, p), (p.actual.int = 85)),
    text: (c) => `${n(c.p)}의 회사가 개발한 AI 칩이 세계 시장을 흔든다. 글로벌 빅테크가 인수를 제안했다.`,
    a: ['인수를 거절하고 독자 노선', 'int', 72, '💻 시가총액 100조! 세계 10대 빅테크가 됐다.', '경쟁사의 반격에 밀렸다.'],
    b: ['글로벌 인재를 끌어모은다', 'cha', 68, '💻 실리콘밸리를 넘어섰다! 빅테크 창업주.', '인재 유출이 일어났다.'] },
  { card: 'hedge_fund', title: '📈 월가 진출', ok: (_s, p) => jobIn(p, ['analyst', 'banker'], 3), setup: setJob('analyst', 4),
    text: (c) => `${n(c.p)}의 예측이 3년 연속 적중했다. 뉴욕 헤지펀드가 운용역을 제안한다.`,
    a: ['공격적 운용', 'int', 64, '📈 수익률 80%! 월가의 전설이 됐다.', '한 번의 베팅으로 큰 손실. 귀국했다.'],
    b: ['리스크 관리 중심', 'mor', 58, '📈 위기에도 살아남은 펀드. 억만장자 반열에.', '평범한 성적으로 끝났다.'] },
  { card: 'ent_chair', title: '🎙 K-콘텐츠 기획사', ok: (s, p) => (jobIn(p, ['entertainer', 'musician', 'actor'], 4) && age(s, p) >= 40) || jobIn(p, ['founder'], 3), setup: setJob('founder', 3),
    text: (c) => `${n(c.p)}이(가) 키운 신인 그룹이 해외에서 반응이 온다. 기획사를 그룹으로 키울 기회.`,
    a: ['글로벌 오디션을 연다', 'cha', 62, '🎙 월드 투어 매진! 엔터 그룹 의장이 됐다.', '투자만 날렸다.'],
    b: ['음악으로 승부', 'int', 60, '🎙 빌보드 1위 그룹 탄생! 문화훈장.', '데뷔가 늦어졌다.'] },
  { card: 'media_mogul', title: '📡 방송사 인수', ok: (_s, p) => jobIn(p, ['founder'], 3) || jobIn(p, ['pd', 'journalist'], 4), setup: setJob('founder', 3),
    text: (c) => `경영난에 빠진 종합편성채널이 매물로 나왔다. ${n(c.p)}이(가) 인수전에 뛰어든다.`,
    a: ['공격적 인수', 'int', 60, '📡 인수 성공! 미디어 그룹 회장이 됐다.', '재벌 계열사에 밀렸다.'],
    b: ['시청자 신뢰로', 'mor', 58, '📡 "신뢰받는 언론"으로 재건했다.', '인수 자금이 부족했다.'] },
  { card: 'space_founder', title: '🛰 로켓 발사', stages: 2, pre: 'bigtech', ok: (s, p) => has(s, p, 'bigtech') || has(s, p, 'astronaut'), setup: setJob('founder', 5),
    text: (c) => `${n(c.p)}이(가) 세운 우주기업의 재사용 로켓이 발사대에 섰다. 전 세계 생중계.`,
    a: ['예정대로 발사', 'int', 74, '🛰 발사와 착륙 모두 성공! 인류의 화성 시대를 연다.', '공중 폭발. 처음부터 다시.'],
    b: ['한 번 더 점검 후 발사', 'mor', 64, '🛰 완벽한 궤도 진입! 민간 우주 시대의 아이콘.', '점검 중 결함이 발견됐다.'] },
  { card: 'heritage_master', title: '🏺 무형문화재 지정', ok: (s, p) => has(s, p, 'master_craft') || (['carpenter', 'chef', 'painter', 'musician'].includes(p.job) && p.jobYears >= 25), setup: (_s, p) => ((p.job = 'carpenter'), (p.jobYears = 30)),
    text: (c) => `${n(c.p)}이(가) 평생 지켜온 전통 기법이 국가무형문화재 지정 심사에 올랐다.`,
    a: ['전통 그대로 시연', 'str', 58, '🏺 국가무형문화재 보유자 인정! 제자들이 몰려온다.', '보류됐다. 기록을 더 쌓아야 한다.'],
    b: ['제자를 길러 전승', 'mor', 58, '🏺 지정! "살아 있는 문화재".', '심사위원들이 고개를 저었다.'] },
  { card: 'maestro', title: '🎼 베를린 필 데뷔', stages: 2, ok: (_s, p) => jobIn(p, ['musician'], 4) && ST(p, 'cha', 70), setup: (s, p) => (setJob('musician', 4)(s, p), (p.actual.cha = 85)),
    text: (c) => `베를린 필하모닉이 ${n(c.p)}을(를) 객원 지휘자로 초청했다. 세계 클래식계의 심장이다.`,
    a: ['과감한 해석', 'cha', 72, '🎼 기립 박수 15분! 세계적 거장의 반열에 올랐다.', '평단은 엇갈렸다.'],
    b: ['악보에 충실한 정통 해석', 'int', 68, '🎼 "완벽한 연주"라는 찬사. 상임 지휘자 제의.', '무난했지만 인상은 약했다.'] },
  { card: 'cannes', title: '🌴 칸 경쟁 부문', stages: 2, ok: (s, p) => has(s, p, 'best_actor') || jobIn(p, ['pd'], 4), setup: setJob('pd', 5),
    text: (c) => `${n(c.p)}의 작품이 칸 영화제 경쟁 부문에 초청됐다. 레드카펫이 기다린다.`,
    a: ['작품성으로', 'int', 70, '🌴 황금종려상! 한국 영화사를 새로 썼다.', '수상은 불발. 그래도 기립박수 8분.'],
    b: ['배우들의 연기로', 'cha', 70, '🌴 연기상 수상! 세계적 배우가 됐다.', '아쉽게 빈손.'] },
  { card: 'pulitzer', title: '🗞 탐사 보도', stages: 2, ok: (_s, p) => jobIn(p, ['journalist'], 2) && ST(p, 'mor', 65), setup: (s, p) => (setJob('journalist', 3)(s, p), (p.actual.mor = 85)),
    text: (c) => `${n(c.p)} 기자가 다국적 기업의 아동 노동 착취를 1년째 추적 중이다. 협박 전화가 온다.`,
    a: ['끝까지 보도한다', 'mor', 70, '🗞 퓰리처상 수상! 국제 공조 수사가 시작됐다.', '소송에 휘말려 보도가 막혔다.'],
    b: ['국제 탐사보도 연합과 협업', 'int', 66, '🗞 세계 동시 보도! 퓰리처상.', '공동 취재가 틀어졌다.'] },
  { card: 'grammy', title: '🏆 그래미 어워드', stages: 2, pre: 'national_singer', ok: (s, p) => has(s, p, 'national_singer') || has(s, p, 'billboard'), setup: setJob('musician', 4),
    text: (c) => `${n(c.p)}이(가) 프로듀싱한 앨범이 그래미 "올해의 앨범" 후보에 올랐다.`,
    a: ['시상식 무대에 선다', 'cha', 72, '🏆 그래미 수상! 한국인 최초.', '수상은 못 했지만 무대가 화제.'],
    b: ['다음 앨범으로 증명', 'int', 70, '🏆 2년 연속 후보 끝에 수상!', '또 후보에만 그쳤다.'] },
  { card: 'esports_owner', title: '🕹 구단 창단', ok: (s, p) => has(s, p, 'gamer_champ') || jobIn(p, ['founder'], 2), setup: setJob('founder', 2),
    text: (c) => `${n(c.p)}이(가) e스포츠 구단을 창단한다. 월드 챔피언십 우승이 목표다.`,
    a: ['스타 선수 영입', 'cha', 58, '🕹 창단 3년 만에 월드 챔피언! 구단 가치가 치솟는다.', '성적이 저조했다.'],
    b: ['유망주 육성', 'int', 58, '🕹 키운 선수들이 세계를 제패했다.', '유망주들이 이적했다.'] },
  { card: 'great_author', title: '🖋 노벨문학상', stages: 2, ok: (_s, p) => jobIn(p, ['novelist'], 4), setup: setJob('novelist', 5),
    text: (c) => `스웨덴 한림원 발표 날. ${n(c.p)}의 이름이 후보로 거론된다.`,
    a: ['평소처럼 원고를 쓴다', 'int', 76, '🖋 노벨문학상 수상! 온 나라가 축제다.', '올해는 다른 작가에게. 내년에 또.'],
    b: ['번역가와 해외 독자를 넓힌다', 'cha', 70, '🖋 수상! 전 세계가 한국 문학을 읽는다.', '번역이 원작을 못 살렸다.'] },
  { card: 'eco_hero', title: '🌱 기후 운동', ok: (s, p) => ST(p, 'mor', 72) && s.fame >= 40 && age(s, p) >= 20, setup: (s, p) => ((p.actual.mor = 90), (s.fame = 60), (p.birthYear = s.year - 35)),
    text: (c) => `${n(c.p)}이(가) 시작한 탄소 감축 캠페인이 세계로 번진다. 유엔 기후총회 연설 초청이 왔다.`,
    a: ['진심을 담아 연설', 'mor', 70, '🌱 타임 올해의 인물 선정!', '연설은 화제가 됐지만 곧 잊혔다.'],
    b: ['실천 프로젝트를 확장', 'int', 62, '🌱 1억 그루 나무 심기 달성! 세계적 환경 영웅.', '자금이 부족했다.'] },
  { card: 'profiler', title: '🔍 연쇄 사건', ok: (_s, p) => jobIn(p, ['police'], 2) && ST(p, 'int', 60), setup: (s, p) => (setJob('police', 3)(s, p), (p.actual.int = 80)),
    text: (c) => `3년째 미궁인 연쇄 사건. ${n(c.p)}이(가) 범행 패턴에서 이상한 점을 발견했다.`,
    a: ['프로파일링으로 좁힌다', 'int', 66, '🔍 검거! "한국의 마인드헌터"로 불린다.', '용의자를 놓쳤다.'],
    b: ['잠복 수사', 'str', 60, '🔍 현장에서 검거!', '잠복이 노출됐다.'] },
  { card: 'explorer', title: '🧭 탐험대', ok: (_s, p) => ['athlete', 'officer', 'researcher', 'navigator', 'photographer', 'trainer'].includes(p.job) && ST(p, 'str', 62) && ST(p, 'hp', 62), setup: (_s, p) => ((p.job = 'athlete'), (p.actual.str = 85), (p.actual.hp = 85)),
    text: (c) => `남극점 무보급 횡단 탐험대. ${n(c.p)}이(가) 대장으로 추천됐다. 60일, 영하 50도.`,
    a: ['끝까지 걷는다', 'hp', 66, '🧭 세계 최초 무보급 횡단 성공! 국기를 꽂았다.', '동상으로 중도 포기. 살아 돌아온 게 다행이다.'],
    b: ['과학 탐사를 겸한다', 'int', 60, '🧭 새로운 빙하 데이터를 가져왔다. 탐험가로 이름을 날렸다.', '장비 고장으로 철수.'] },
  { card: 'cardinal', title: '⛪ 추대', stages: 2, ok: (_s, p) => jobIn(p, ['clergy'], 2) && ST(p, 'mor', 70), setup: (s, p) => (setJob('clergy', 3)(s, p), (p.actual.mor = 90)),
    text: (c) => `평생 가난한 이들 곁을 지킨 ${n(c.p)}이(가) 종단 최고 지도자로 추대된다는 소식.`,
    a: ['낮은 곳으로 간다', 'mor', 74, '⛪ 추대됐다. 온 국민이 존경하는 어른이 됐다.', '종단 내 갈등으로 무산됐다.'],
    b: ['종교 간 화합을 이끈다', 'cha', 66, '⛪ 추대! 종교를 넘어선 화합의 상징.', '보수파의 반대에 부딪혔다.'] },
  { card: 'conscience', title: '🕯 거리의 양심', ok: (_s, p) => ['journalist', 'lawyer', 'professor', 'clergy', 'social_worker', 'writer', 'novelist'].includes(p.job) && ST(p, 'mor', 75), setup: (_s, p) => ((p.job = 'lawyer'), (p.actual.mor = 90)),
    text: (c) => `부당한 권력에 맞선 시민들이 거리로 나섰다. ${n(c.p)}에게 앞에 서 달라는 요청이 온다.`,
    a: ['앞장선다', 'mor', 72, '🕯 역사가 바뀌었다. "시대의 양심"으로 기억된다.', '연행됐다. 그래도 물러서지 않았다.'],
    b: ['글과 변론으로 싸운다', 'int', 64, '🕯 그의 글이 세상을 움직였다.', '탄압을 받았다.'] },
  { card: 'model_civil', title: '🏛 청렴 표창', ok: (_s, p) => jobIn(p, ['civil', 'tax_officer', 'mail_carrier', 'prison_guard', 'public_corp'], 1), setup: (s, p) => (setJob('civil', 1)(s, p)),
    text: (c) => `${n(c.p)}이(가) 10년 넘게 민원 칭찬 1위다. 청렴 공무원 후보에 올랐다.`,
    a: ['원칙을 지킨 기록을 낸다', 'mor', 45, '🏛 청백리 표창! 가문 이름이 관보에 실렸다.', '아깝게 떨어졌다.'],
    b: ['민원인들의 추천서를 받는다', 'cha', 45, '🏛 표창! 주민들이 떡을 돌렸다.', '추천서가 모자랐다.'] },
  { card: 'best_teacher', title: '🍎 스승의 날', ok: (_s, p) => jobIn(p, ['teacher', 'kinder_teacher', 'tutor', 'librarian'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('teacher', 0)(s, p)),
    text: (c) => `스승의 날, 졸업생들이 ${n(c.p)}을(를) "올해의 스승"으로 추천했다.`,
    a: ['수업 영상을 낸다', 'cha', 45, '🍎 올해의 스승 선정! 제자들이 꽃다발을 들고 왔다.', '이번엔 다른 선생님이 뽑혔다.'],
    b: ['제자들의 편지를 모은다', 'mor', 45, '🍎 선정! 편지 한 통 한 통에 눈물이 났다.', '아쉽게 떨어졌다.'] },
  { card: 'sales_king', title: '🥇 연말 시상식', ok: (_s, p) => jobIn(p, ['office', 'corp', 'sales', 'insurance', 'marketer', 'trader', 'banker', 'hr', 'secretary', 'analyst'], 1), setup: (s, p) => (setJob('office', 1)(s, p)),
    text: (c) => `연말 시상식. ${n(c.p)}이(가) 올해 실적 최상위 후보다.`,
    a: ['마지막 달 영업에 올인', 'cha', 45, '🥇 영업왕! 트로피와 해외 연수권을 받았다.', '2위. 내년엔 꼭.'],
    b: ['숫자로 증명하는 보고서', 'int', 45, '🥇 최우수 사원상!', '보고서가 묻혔다.'] },
  { card: 'engineer_award', title: '⚙️ 사내 기술상', ok: (_s, p) => jobIn(p, ['developer', 'data_scientist', 'security', 'game_dev', 'researcher', 'chip_engineer', 'mech_engineer', 'aero_engineer', 'architect'], 1), setup: (s, p) => (setJob('developer', 1)(s, p)),
    text: (c) => `${n(c.p)}이(가) 만든 기술이 회사 비용을 크게 줄였다. 기술상 후보다.`,
    a: ['기술 발표를 한다', 'int', 45, '⚙️ 올해의 엔지니어! 사내 명예의 전당에 사진이 걸렸다.', '다른 팀이 받았다.'],
    b: ['팀원들에게 공을 돌린다', 'mor', 45, '⚙️ 수상! 팀 전체가 박수를 쳤다.', '아쉽게 빈손.'] },
  { card: 'service_master', title: '🎀 친절 명인', ok: (_s, p) => jobIn(p, ['chef', 'barista', 'hairdresser', 'nail_artist', 'hotelier', 'flight_attendant', 'tour_guide', 'wedding_planner', 'pet_groomer'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('chef', 0)(s, p)),
    text: (c) => `손님 칭찬 카드가 쌓였다. ${n(c.p)}이(가) 업계 "친절 명인" 후보에 올랐다.`,
    a: ['현장 심사를 받는다', 'cha', 45, '🎀 서비스 명인 선정! 단골이 두 배로 늘었다.', '심사 날 실수를 했다.'],
    b: ['후배 교육 실적을 낸다', 'mor', 45, '🎀 명인 선정!', '떨어졌다.'] },
  { card: 'good_driver', title: '🚌 무사고 표창', ok: (_s, p) => jobIn(p, ['courier', 'delivery_rider', 'taxi', 'bus_driver', 'trucker', 'train_driver', 'navigator', 'pilot'], 0) && p.jobYears >= 5, setup: (s, p) => (setJob('courier', 0)(s, p)),
    text: (c) => `${n(c.p)}의 무사고 기록이 이어지고 있다. 교통안전공단 표창 후보다.`,
    a: ['마지막까지 안전 운행', 'mor', 42, '🚌 무사고 모범 기사 표창!', '작은 접촉 사고로 기록이 끊겼다.'],
    b: ['동료 안전 교육에 나선다', 'cha', 42, '🚌 표창! 회사 대표 강사가 됐다.', '다음 해를 기약한다.'] },
  { card: 'local_legend', title: '🏮 생활의 달인 섭외', ok: (_s, p) => jobIn(p, ['shopkeeper', 'cafe_owner', 'cvs_owner', 'online_shop', 'restaurant', 'founder'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('shopkeeper', 0)(s, p)),
    text: (c) => `TV 생활 프로그램 작가가 ${n(c.p)}의 가게를 찾아왔다. "동네 명물로 소개하고 싶어요."`,
    a: ['비법을 공개한다', 'cha', 45, '🏮 방송 후 줄이 섰다! 동네 명물이 됐다.', '편집에서 잘렸다.'],
    b: ['손님들 이야기를 담는다', 'mor', 45, '🏮 따뜻한 방송이 화제가 됐다.', '방송이 밀렸다.'] },
  { card: 'angel_care', title: '🤍 봉사상', ok: (_s, p) => jobIn(p, ['nurse', 'pt', 'radiographer', 'clinical', 'emt', 'nurse_aide', 'caregiver', 'vet'], 0) && p.jobYears >= 5, setup: (s, p) => (setJob('nurse', 0)(s, p)),
    text: (c) => `${n(c.p)}이(가) 돌본 환자 가족들이 봉사상 추천서를 보냈다.`,
    a: ['야간 봉사 기록을 낸다', 'mor', 45, '🤍 백의의 천사상!', '아쉽게 떨어졌다.'],
    b: ['환자들의 편지를 모은다', 'cha', 42, '🤍 수상! 병원 로비에 사진이 걸렸다.', '다음 기회에.'] },
  { card: 'pro_license', title: '📑 협회 공로상', ok: (_s, p) => jobIn(p, ['lawyer', 'accountant', 'tax_accountant', 'patent_attorney', 'scrivener', 'appraiser', 'labor_attorney', 'customs_broker', 'realtor'], 0) && p.jobYears >= 5, setup: (s, p) => (setJob('lawyer', 0)(s, p)),
    text: (c) => `협회가 ${n(c.p)}에게 공로상 후보를 알려 왔다. 무료 상담 실적이 쌓였다.`,
    a: ['공익 활동을 내세운다', 'mor', 45, '📑 업계의 명인으로 인정받았다!', '다른 사람이 받았다.'],
    b: ['실무 실력으로', 'int', 45, '📑 공로상 수상!', '아쉽게 떨어졌다.'] },
  { card: 'craft_hands', title: '🔨 기능 우수상', ok: (_s, p) => jobIn(p, ['factory', 'big_factory', 'electrician', 'welder', 'mechanic', 'carpenter', 'plumber', 'shipbuilder', 'crane_operator'], 0) && p.jobYears >= 5, setup: (s, p) => (setJob('factory', 0)(s, p)),
    text: (c) => `공장장이 ${n(c.p)}을(를) 기능 우수상 후보로 올렸다.`,
    a: ['실기 시연', 'str', 45, '🔨 기능 우수상! 후배들이 비법을 배우러 온다.', '실수가 나왔다.'],
    b: ['불량률 개선 기록', 'int', 42, '🔨 수상!', '기록이 조금 모자랐다.'] },
  { card: 'rookie_star', title: '🌠 신인상', ok: (_s, p) => jobIn(p, ['entertainer', 'actor', 'model', 'musician', 'writer', 'novelist', 'painter', 'photographer', 'youtuber', 'voice_actor', 'journalist', 'pd', 'announcer', 'athlete', 'gamer', 'designer'], 0) && p.jobYears >= 1, setup: (s, p) => (setJob('entertainer', 0)(s, p)),
    text: (c) => `올해 ${n(c.p)}이(가) 신인상 후보에 올랐다. 시상식 날이다.`,
    a: ['당당하게 무대에', 'cha', 48, '🌠 신인상! 첫 트로피를 가족에게 바쳤다.', '다른 신인이 받았다.'],
    b: ['작품(기록)으로 승부', 'int', 45, '🌠 신인상 수상!', '아쉽게 빈손.'] },
  { card: 'farm_hero', title: '🌽 풍년 표창', ok: (_s, p) => jobIn(p, ['farmer', 'smart_farmer', 'fisher', 'rancher'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('farmer', 0)(s, p)),
    text: (c) => `올해 ${n(c.p)}의 수확이 군에서 제일 좋다. 농업인의 날 표창 후보다.`,
    a: ['품질 심사', 'str', 42, '🌽 풍년 표창! 마을 잔치가 열렸다.', '심사에서 아쉽게.'],
    b: ['이웃과 나눈 기록', 'mor', 42, '🌽 표창! 이웃들이 박수를 쳤다.', '다음 해를 기약.'] },
  { card: 'public_servant', title: '🎗 모범 공무원', ok: (_s, p) => jobIn(p, ['police', 'coast_guard', 'firefighter', 'officer', 'diplomat', 'judge', 'prosecutor'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('police', 0)(s, p)),
    text: (c) => `${n(c.p)}이(가) 모범 공무원 후보에 올랐다. 제복을 입은 지 여러 해.`,
    a: ['현장 공적을 낸다', 'str', 45, '🎗 모범 공무원 표창! 제복이 더 자랑스럽다.', '이번엔 동료가 받았다.'],
    b: ['헌신의 기록을 낸다', 'mor', 45, '🎗 표창!', '아쉽게 떨어졌다.'] },
  { card: 'good_heart', title: '💝 지역 봉사상', ok: (_s, p) => jobIn(p, ['social_worker', 'clergy', 'doctor', 'dentist', 'kmd', 'pharmacist'], 0) && p.jobYears >= 3, setup: (s, p) => (setJob('social_worker', 0)(s, p)),
    text: (c) => `${n(c.p)}의 무료 진료·봉사가 입소문이 났다. 지역 봉사상 후보다.`,
    a: ['봉사를 계속한다', 'mor', 45, '💝 나눔의 손길상!', '다른 분이 받았다.'],
    b: ['이웃을 모아 함께한다', 'cha', 42, '💝 수상! 봉사단이 생겼다.', '아쉽게.'] },
  { card: 'filial', title: '🙇 효행상', ok: (s, p) => age(s, p) >= 25 && p.actual.mor >= 55 && p.affinity >= 40 && [p.fatherId, p.motherId].some((id) => id && s.people[id] && s.people[id].deathYear === undefined && age(s, s.people[id]) >= 65), setup: (s, p) => ((p.actual.mor = 80), (p.affinity = 80), (p.birthYear = s.year - 40), (s.people[p.fatherId!].birthYear = s.year - 70), (s.people[p.fatherId!].deathYear = undefined)),
    text: (c) => `아픈 부모님을 극진히 모시는 ${n(c.p)}의 이야기가 동네에 퍼졌다. 구청이 효행상 후보로 올렸다.`,
    a: ['겸손히 받는다', 'mor', 45, '🙇 효행상! 부모님이 상장을 머리맡에 두셨다.', '더 어려운 분께 양보했다.'],
    b: ['가족 모두 함께한 일이라 말한다', 'cha', 42, '🙇 수상! 가족 사진이 신문에 실렸다.', '아쉽게.'] },
];
