// 모든 이벤트 모음 (모듈 간 순환 참조를 피하려고 따로 둔다)
import { EVENTS as CORE, RANDOM_EVENTS } from './events';
import { SCHOOL_EVENTS } from './school';
import { FAMILY_EVENTS } from './family';
import { LIFE_EVENTS } from './life';
import { FATE_EVENTS, FATE_RANDOM } from './fate';
import { ROMANCE_EVENTS, ROMANCE_RANDOM } from './romance';
import { STORIES } from './stories';
import { SEED_EVENTS } from './seeds';
import { NEST_EVENTS } from './nest';
import { WOE_EVENTS } from './woes';
import { HIST_EVENTS } from './history';
import { FUTURE_EVENTS } from './timeline';
import { CHAIN_EVENTS } from './chains';
import { WAR_EVENTS } from './war';
import { MEDICAL_EVENTS } from './medical-events';
import { EGG_EVENTS } from './nestegg';
import { SPOUSE_EVENTS } from './spouse';
import { ALLOWANCE_EVENTS } from './allowance';
import { TENANT_EVENTS } from './tenant';
import { DEBT_EVENTS } from './debt';
import { LEVERAGE_EVENTS } from './leverage';
import { LIFECOST_EVENTS } from './lifecost';
import { DECEPTION_EVENTS } from './deception';
import { HOBBY_EVENT } from './interests';
import { WELFARE_EVENTS } from './welfare';
import { RIVAL_EVENTS } from './rival';
import { ERA_EVENTS } from './era';
import { CAREER_EVENTS } from './career';
import { CARD_EVENTS } from './cards';
import { SCANDAL_EVENTS } from './scandal';
import { AUTONOMY_EVENTS } from './autonomy';
import { HIDDEN_EVENTS } from './hidden';
import { INLAW_EVENTS } from './inlaws';
import { SUPER_HIDDEN_EVENTS } from './super-hidden';
import { GATE_EVENTS } from './super-gates';
import { PATH_EVENTS } from './hidden-paths';
import { PHOTO_EVENTS } from './photos';
import { RELIC_EVENTS } from './relics';
import { VIP_EVENTS } from './vip-cure';
import { BIG_EVENTS } from './big-events';
import { CRIME_EVENTS } from './crimes';
import { POWER_EVENTS } from './power';
import { DUTY_EVENTS } from './duty';
import { POWER2_EVENTS } from './power2';
import { HANDOVER_EVENTS } from './handover';
import type { EventDef } from './ev-util';

export const EVENTS: Record<string, EventDef> = { ...CORE, ...Object.fromEntries([...SCHOOL_EVENTS, ...FAMILY_EVENTS, ...LIFE_EVENTS, ...FATE_EVENTS, ...FATE_RANDOM, ...ROMANCE_EVENTS, ...ROMANCE_RANDOM, ...STORIES, ...SEED_EVENTS, ...NEST_EVENTS, ...DEBT_EVENTS, ...LEVERAGE_EVENTS, ...LIFECOST_EVENTS, ...DECEPTION_EVENTS, HOBBY_EVENT, ...WELFARE_EVENTS, ...RIVAL_EVENTS, ...ERA_EVENTS, ...CAREER_EVENTS, ...CARD_EVENTS, ...SCANDAL_EVENTS, ...AUTONOMY_EVENTS, ...WOE_EVENTS, ...EGG_EVENTS, ...SPOUSE_EVENTS, ...ALLOWANCE_EVENTS, ...TENANT_EVENTS, ...HIST_EVENTS, ...FUTURE_EVENTS, ...CHAIN_EVENTS, ...WAR_EVENTS, ...MEDICAL_EVENTS, ...HIDDEN_EVENTS, ...INLAW_EVENTS, ...SUPER_HIDDEN_EVENTS, ...GATE_EVENTS, ...PATH_EVENTS, ...PHOTO_EVENTS, ...RELIC_EVENTS, ...VIP_EVENTS, ...BIG_EVENTS, ...CRIME_EVENTS, ...POWER_EVENTS, ...DUTY_EVENTS, ...POWER2_EVENTS, ...HANDOVER_EVENTS].map((e) => [e.id, e])) };
export { RANDOM_EVENTS };
